language: android
jdk: oraclejdk8
android:
  components:
    # The following 3 are needed to update the version of the SDK Travis provides.
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by the project
    - build-tools-28.0.2
    # The SDK version used to compile the project
    - android-28

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew build connectedCheck

notifications:
  email: false
  slack: $SLACK_ACCOUNT:$SLACK_TOKEN#builds
